name: Test 2023 solutions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      working-directory: ./2023
      run: for dir in ./*; do (cd "$dir" && cargo test --verbose); done
